I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 218, in script call
    python:
  File "renpy/common/00start.rpy", line 94, in script
    return
Exception: Could not find return label (u"C:\\Users\\Daniel\\Desktop\\emu\\Ren'Py test project\\Anechoic Chamber/game/script.rpy", 1472380231, 4).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 218, in script call
    python:
  File "renpy/common/00start.rpy", line 94, in script
    return
  File "C:\Users\Daniel\Desktop\emu\renpy\renpy-6.99.10-sdk\renpy\ast.py", line 1368, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Daniel\Desktop\emu\renpy\renpy-6.99.10-sdk\renpy\execution.py", line 523, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u"C:\\Users\\Daniel\\Desktop\\emu\\Ren'Py test project\\Anechoic Chamber/game/script.rpy", 1472380231, 4).

Windows-7-6.1.7600
Ren'Py 6.99.10.1227
Anechoic Chamber 0.0
